INSERT INTO sources (platform,name,url,kind,region,status,priority,discovered_by) VALUES
('instagram','ARABA KIBRIS','https://www.instagram.com/kibris.car/','ilan_sayfasi','KKTC','aktif',1,'seed'),
('instagram','KKTC SINIRLARINDA ARAC SATISI','https://www.instagram.com/arabam.kibris_/','ilan_sayfasi','KKTC','aktif',1,'seed'),
('instagram','ARAC KIBRIS','https://www.instagram.com/arac.kibriis/','ilan_sayfasi','KKTC','aday',1,'seed'),
('instagram','KKTC Ikinci El Arac Satis','https://www.instagram.com/araba.kktc/','ilan_sayfasi','KKTC','aday',2,'seed'),
('instagram','KKTC IKINCI EL SATILIK ARACLAR','https://www.instagram.com/kibris__arabam/','ilan_sayfasi','KKTC','aday',1,'seed'),
('instagram','KKTC ARABAM','https://www.instagram.com/kktc_arabam/','ilan_sayfasi','KKTC','aday',1,'seed'),
('instagram','SARI SAYFA','https://www.instagram.com/kktc.arabalari/','ilan_sayfasi','KKTC','aday',1,'seed'),
('instagram','KKTC Arabam','https://www.instagram.com/kibrisarabam_/','ilan_sayfasi','KKTC','aday',3,'seed'),
('instagram','KKTC Ikinci El Satilik Araba','https://www.instagram.com/kibris_arabam/','ilan_sayfasi','KKTC','aday',2,'seed'),
('instagram','KKTC IKINCI EL ARAC SATIS','https://www.instagram.com/araba._.kibris/','ilan_sayfasi','KKTC','aday',2,'seed'),
('instagram','ASAL OTO GALERI','https://www.instagram.com/asal.otogaleri/','galeri','KKTC','aday',3,'seed'),
('facebook','KKTC ARABA PAZARI','https://www.facebook.com/groups/469402498541872/','grup','KKTC','aday',1,'seed'),
('facebook','Kktc Sol Direksiyon Araba Pazari','https://www.facebook.com/groups/1797997293768755/','grup','KKTC','aday',2,'seed'),
('facebook','north cyprus cars and bikes for sale','https://www.facebook.com/groups/539378399490159/','grup','KKTC','aday',1,'seed'),
('facebook','KKTC ARABAM','https://www.facebook.com/groups/Kibris.Arabam/','grup','KKTC','aday',1,'seed'),
('facebook','KKTC ARABA SATIS GRUBU','https://www.facebook.com/groups/460146661032088/','grup','KKTC','aday',1,'seed'),
('facebook','KKTC Araba Alim Satim','https://www.facebook.com/groups/405189333280604/','grup','KKTC','aday',1,'seed'),
('facebook','KKTC SATILIK ARABA','https://www.facebook.com/groups/414145832006081/','grup','KKTC','aday',1,'seed'),
('facebook','MERCEDES BENZ ALIM SATIM GRUBU KKTC','https://www.facebook.com/groups/682061759485628/','grup','KKTC','aday',3,'seed'),
('facebook','CARS FOR SALE CYPRUS','https://www.facebook.com/groups/457664067768891/','grup','karisik','aday',3,'seed'),
('facebook','Cyprus Cars for sale or swap','https://www.facebook.com/groups/CYPRUSCARSFORSALEORSWAP/','grup','karisik','aday',3,'seed'),
('facebook','Marketplace Cars Kyrenia','https://www.facebook.com/marketplace/2100962630160679/cars/','marketplace','karisik','aday',2,'seed'),
('facebook','Marketplace Cars Nicosia','https://www.facebook.com/marketplace/110929015601194/cars/','marketplace','karisik','aday',3,'seed'),
('telegram','NORTH CYPRUS CARS','https://t.me/cypruscars','grup','KKTC','aktif',1,'seed'),
('telegram','SEVERNIY KIPR BARAHOLKA','https://t.me/cyprusfleamarket','grup','KKTC','aktif',2,'seed'),
('telegram','BARAHOLKA SEVERNIY KIPR','https://t.me/barakholka_northcyprus','grup','KKTC','aday',3,'seed'),
('telegram','Severniy Kipr CHAT','https://t.me/Life_Northern_Cyprus','grup','KKTC','aday',3,'seed'),
('telegram','Cyprus Car','https://t.me/cypruscar','kanal','Guney','disari',0,'seed'),
('telegram','Cyprus Car Sale','https://t.me/cypruscar_sale','kanal','Guney','disari',0,'seed'),
('web','KKTCarabam','https://www.kktcarabam.com/kategori/ikinci-el-araclar','ilan_sitesi','KKTC','aktif',1,'seed'),
('web','KKTCar','https://kktcar.com/en/search/results','ilan_sitesi','KKTC','aktif',1,'seed'),
('web','Kibris Araba Al','https://www.kibrisarabaal.com','ilan_sitesi','KKTC','aktif',1,'seed'),
('web','Mezunum Satiyorum','https://mezunumsatiyorumkibris.com.tr/ilanlar/kktc-araba','ilan_sitesi','KKTC','aktif',1,'seed'),
('web','Sahibinden Araba Kibris','https://sahibindenarabakibris.com','ilan_sitesi','KKTC','aktif',2,'seed'),
('web','Sahibinden KKTC','https://www.sahibindenkktc.com','ilan_sitesi','KKTC','aday',3,'seed'),
('web','KibrisAraba','https://www.kibrisaraba.com/','ilan_sitesi','KKTC','erisim_reddediyor',0,'seed'),
('web','GalerimPlus','https://www.galerimplus.com','ilan_sitesi','KKTC','erisim_reddediyor',0,'seed'),
('web','Illaki Burada','https://www.illakiburada.com/17/vasita-otomobil','ilan_sitesi','KKTC','erisim_reddediyor',0,'seed')
ON CONFLICT (url) DO NOTHING;